name: Angular Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  # Or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build -- --configuration production --base-href jz-salon  # Replace with your repo name

      - name: Deploy to GitHub Pages
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.2 # or the latest version
        with:
          # The folder the action should deploy
          deploy_path: dist/jz-salon # Replace with your dist folder
          # The branch the action should deploy to
          deploy_branch: gh-pages # or your configured deployment branch
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
